[field_mapping]
id = "id"
loaiGiayPhepId = "loaiGiayPhepId"
loaiGiayPhep = "loaiGiayPhep"
xuPhatId = "xuPhatId"
xuPhat = "xuPhat"
soGiayPhep = "soGiayPhep"
ngayCapGiayPhep = "ngayCapGiayPhep"
tenCongTy = "tenCongTy"
tenVietTat = "tenVietTat"
nguoiDaiDien = "nguoiDaiDien"
diaChi = "diaChi"
soDienThoai = "soDienThoai"
soFax = "soFax"
email = "email"
loaiHinhId = "loaiHinhId"
loaiHinh = "loaiHinh"
vonDieuLe = "vonDieuLe"

